spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: test-dev-java-group
      enable-auto-commit: false
      max-poll-records: 10
      properties:
        max.poll.interval.ms: 60000
        session.timeout.ms: 60000
    listener:
      concurrency: 4
  datasource:
    url: jdbc:postgresql://localhost:5432/test_dev_db
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog.xml
    enabled: true
kafka:
  transaction-event.name: transaction.event.topic
  notification-event.name: notification.event.topic